# Generated by Django 4.2.9 on 2024-04-03 09:13

from django.db import migrations
import petstagram.accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_petstagramuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='petstagramuser',
            managers=[
                ('objects', petstagram.accounts.managers.PetstagramUserManager()),
            ],
        ),
    ]
