# Generated by Django 5.0.4 on 2024-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstagramuser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
