# Generated by Django 5.0.4 on 2024-04-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_petphoto_likes_count_alter_petphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.URLField(),
        ),
    ]
