# Generated by Django 5.0.4 on 2024-04-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petevent',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
