# Generated by Django 5.0.4 on 2024-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptablePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='adoptable_pets/')),
                ('adoption_status', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
