# Generated by Django 5.0.4 on 2024-04-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptablepet',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adoptablepet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adoptablepet',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
